
package com.mycompany.appfit;


import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alba
 */
public class FitTrack extends javax.swing.JFrame {

    /**
     * Creates new form Fit
     */
    public FitTrack() {
        
        initComponents();
        setLocationRelativeTo(null);
         
         // Estilo oscuro para la tabla desde el inicio
        jTable1.setBackground(new java.awt.Color(82, 82, 82)); 
        jTable1.setForeground(new java.awt.Color(227,227,227));        
        jTable1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 15));
        jTable1.setRowHeight(24);

        // Encabezado de la tabla
        jTable1.getTableHeader().setBackground(new java.awt.Color(82, 82, 82)); // gris oscuro
        jTable1.getTableHeader().setForeground(java.awt.Color.WHITE);
        jTable1.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        
        
          // centra las celdas de la tabla 
        javax.swing.table.DefaultTableCellRenderer centerRenderer = new javax.swing.table.DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

      

        // carga la imagen desde Internet
        try {
            URL url = new URL("https://static.vecteezy.com/system/resources/previews/003/189/742/non_2x/weightlifting-exercises-chalk-white-icon-on-dark-background-vector.jpg");
            ImageIcon icon = new ImageIcon(url);
            Image imagen = icon.getImage().getScaledInstance(250, 200, Image.SCALE_SMOOTH);
            imagenInternet.setIcon(new ImageIcon(imagen));
            imagenInternet.setText("");
        } catch (Exception e) {
            imagenInternet.setText("No se pudo cargar la imagen desde internet");
        }

        // configura  el Combo principal con tipos de ejercicios
        TipoEjercicio.removeAllItems();
        TipoEjercicio.addItem("");
        TipoEjercicio.addItem("Cardio");
        TipoEjercicio.addItem("Fuerza");
        TipoEjercicio.addItem("Yoga");
        TipoEjercicio.addItem("Otros");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TipoEjercicio = new javax.swing.JComboBox<>();
        subtipo = new javax.swing.JComboBox<>();
        duracion = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        BotonAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        imagenInternet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        logo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        logo.setForeground(new java.awt.Color(0, 0, 0));
        logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\alba_\\Documents\\NetBeansProjects\\AppFit\\logo (2).png")); // NOI18N
        logo.setText("FIT TRACK");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Agregar Entrenamiento");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tipo de ejercicio: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Subtipo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Duración (min):");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha (dd/mm/aaaa):");

        TipoEjercicio.setBackground(new java.awt.Color(82, 82, 82));
        TipoEjercicio.setForeground(new java.awt.Color(229, 227, 227));
        TipoEjercicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardio", "Fuerza", "Yoga", "Otros" }));
        TipoEjercicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TipoEjercicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TipoEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoEjercicioActionPerformed(evt);
            }
        });

        subtipo.setBackground(new java.awt.Color(82, 82, 82));
        subtipo.setForeground(new java.awt.Color(229, 227, 227));
        subtipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subtipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtipoActionPerformed(evt);
            }
        });

        duracion.setBackground(new java.awt.Color(82, 82, 82));
        duracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        duracion.setForeground(new java.awt.Color(229, 227, 227));
        duracion.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionActionPerformed(evt);
            }
        });

        fecha.setBackground(new java.awt.Color(82, 82, 82));
        fecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fecha.setForeground(new java.awt.Color(229, 227, 227));
        fecha.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        BotonAñadir.setBackground(new java.awt.Color(51, 51, 51));
        BotonAñadir.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        BotonAñadir.setForeground(new java.awt.Color(204, 204, 204));
        BotonAñadir.setText("Añadir");
        BotonAñadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAñadirActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(82, 82, 82));
        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(229, 227, 227));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Ejercicio", "Subtipo", "Duracion"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable1.setOpaque(false);
        jTable1.setSelectionForeground(new java.awt.Color(82, 82, 82));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Fecha");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Ejercicio");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Subtipo");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Duracion");
        }

        imagenInternet.setForeground(new java.awt.Color(0, 0, 0));
        imagenInternet.setText("IMAGENINTERNET");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TipoEjercicio, 0, 94, Short.MAX_VALUE)
                                    .addComponent(subtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(duracion)
                                    .addComponent(fecha)))
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imagenInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imagenInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TipoEjercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(subtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(BotonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void subtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtipoActionPerformed
     
    }//GEN-LAST:event_subtipoActionPerformed

    private void TipoEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoEjercicioActionPerformed
        
        // Actualiza los subtipos dependiendo del tipo elegido
        subtipo.removeAllItems();
        String tipo = (String) TipoEjercicio.getSelectedItem();

        if (tipo == null) return;

        switch (tipo) {
            case "Cardio":
                subtipo.addItem("Correr");
                subtipo.addItem("Bicicleta");
                subtipo.addItem("Nadar");
                subtipo.addItem("Cinta de correr");
                break;

            case "Fuerza":
                subtipo.addItem("Pecho");
                subtipo.addItem("Piernas");
                subtipo.addItem("Espalda");
                subtipo.addItem("Bíceps");
                break;

            case "Yoga":
                subtipo.addItem("Postura montaña");
                subtipo.addItem("Perro boca abajo");
                subtipo.addItem("Cobra");
                subtipo.addItem("Puente");
                break;

            case "Otros":
                subtipo.addItem("Senderismo");
                subtipo.addItem("Escalada");
                subtipo.addItem("Surf");
                subtipo.addItem("Padel surf");
                break;
        }

    }//GEN-LAST:event_TipoEjercicioActionPerformed

    private void BotonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAñadirActionPerformed
        
         // recupera los datos introducidos
        String tipo = (String) TipoEjercicio.getSelectedItem();
        String sub = (String) subtipo.getSelectedItem();
        String dur = duracion.getText();
        String fech = fecha.getText();

        // Validaciones básicas
        if (tipo == null || sub == null || dur.isEmpty() || fech.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos antes de añadir.");
            return;
        }

        // añade los datos a la tabla
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{fech, tipo, sub, dur});

        // linmpia los campos
        duracion.setText("");
        fecha.setText("");
        subtipo.setSelectedIndex(-1);
        TipoEjercicio.setSelectedIndex(-1);
    }//GEN-LAST:event_BotonAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> new FitTrack().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAñadir;
    private javax.swing.JComboBox<String> TipoEjercicio;
    private javax.swing.JTextField duracion;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel imagenInternet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> subtipo;
    // End of variables declaration//GEN-END:variables
}
